dist: xenial
branches:
  only:
  - master
language: java
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
jobs:
  include:
  - script:
    - cd close-tickets
    - mvn clean install
    name: Test Close Tickets App
stages:
- test
